# Generated by Django 5.2.1 on 2025-06-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='song_id',
            new_name='track_id',
        ),
    ]
