# Generated by Django 5.2.1 on 2025-06-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_roommember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_song',
            new_name='current_track',
        ),
    ]
